# Generated by Django 3.0.6 on 2020-05-18 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Verified',
            new_name='verified',
        ),
    ]
