# Generated by Django 3.0.6 on 2020-05-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='email_adress',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='email_reply',
        ),
        migrations.AddField(
            model_name='feedback',
            name='email_reply_adress',
            field=models.ManyToManyField(blank=True, limit_choices_to={'verified': True}, to='firstapp.Profile'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='email_reply_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время отправки'),
        ),
    ]
