# Generated by Django 3.0.6 on 2020-05-18 20:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstapp', '0010_auto_20200518_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email_reply_adress',
            field=models.ManyToManyField(blank=True, limit_choices_to={'verified': False}, to=settings.AUTH_USER_MODEL),
        ),
    ]
