# Generated by Django 3.0.6 on 2020-05-19 12:08

import django.contrib.postgres.indexes
from django.db import migrations
from django.contrib.postgres.operations import BtreeGinExtension

class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0012_auto_20200518_2306'),
    ]

    operations = [
        BtreeGinExtension(),
        migrations.AddIndex(
            model_name='book',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='firstapp_bo_name_27ec38_gin'),
        ),
    ]
