# Generated by Django 3.0.6 on 2020-05-19 12:21

import django.contrib.postgres.indexes
from django.db import migrations
from django.contrib.postgres.operations import BtreeGinExtension

class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0013_auto_20200519_1508'),
    ]

    operations = [
        BtreeGinExtension(),
        migrations.RemoveIndex(
            model_name='book',
            name='firstapp_bo_name_27ec38_gin',
        ),
        migrations.AddIndex(
            model_name='book',
            index=django.contrib.postgres.indexes.GinIndex(fields=['age'], name='firstapp_bo_age_0f413f_gin'),
        ),
    ]
