# Generated by Django 3.0.6 on 2020-05-19 13:07

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0015_auto_20200519_1522'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='author',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='firstapp_au_name_37a1ac_gin'),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='firstapp_ge_name_c568fd_gin'),
        ),
    ]
