# Generated by Django 3.0.6 on 2020-05-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0019_auto_20200519_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stbool',
            field=models.BooleanField(default=False),
        ),
    ]
