# Generated by Django 3.0.6 on 2020-05-19 21:08

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0020_student_stbool'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='course',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='firstapp_co_name_832465_gin'),
        ),
    ]
