# Generated by Django 3.0.6 on 2020-05-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0021_auto_20200520_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(related_name='course', to='firstapp.Course'),
        ),
    ]
